repos:
      - repo: https://github.com/ambv/black
        rev: 23.12.1
        hooks:
          - id: black
            args: [--line-length=79]
      - repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.0.0
        hooks:
          - id: flake8
            args: ["--extend-ignore=E203"]

exclude: ^venv/
